name = "GRcoder"
uuid = "bb4f71c6-6854-49f8-896c-4b93bf7dc54b"
authors = ["Paul <ptiede91@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
